name: Dependabot Auto-Merge

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Auto-approve patch and minor updates
        if: >
          steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
          steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: |
          echo "Auto-approving ${{ steps.metadata.outputs.update-type }} update"
          echo "Package: ${{ steps.metadata.outputs.dependency-names }}"
          echo "From: ${{ steps.metadata.outputs.previous-version }}"
          echo "To: ${{ steps.metadata.outputs.new-version }}"
          gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge for patch and minor updates
        if: >
          steps.metadata.outputs.update-type == 'version-update:semver-patch' ||
          steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: |
          echo "Enabling auto-merge with squash strategy"
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Skip major updates
        if: steps.metadata.outputs.update-type == 'version-update:semver-major'
        run: |
          echo "⚠️ Major version update detected - skipping auto-merge"
          echo "Package: ${{ steps.metadata.outputs.dependency-names }}"
          echo "From: ${{ steps.metadata.outputs.previous-version }}"
          echo "To: ${{ steps.metadata.outputs.new-version }}"
          echo "This update requires manual review."
